### PR TITLE
git-week1

### PR DESCRIPTION
**Pull request by NataliaS1994**

### CODE REVIEW

**Review by martamatos — CHANGES_REQUESTED** [review]
Perfect Natalia!!! :D

I have one last task for you (to mimic the process of implementing feedback): can you add one more country to the country3.txt, commit and push please?

**Comment by NataliaS1994** [comment]
> Perfect Natalia!!! :D
> 
> I have one last task for you (to mimic the process of implementing feedback): can you add one more country to the country3.txt, commit and push please?

**Comment by NataliaS1994** [comment]
Hi @martamatos! :)
I added one more country to the country3 folder. Shall I merge now ? :D

**Comment by martamatos** [comment]
Yes please! :D

**Pull request merged**
